name: morning-alert

on: push

jobs:
  super-lint:
    name: check part
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Every time
        run: echo ${PATH}
#         env:
#           DEFAULT_BRANCH: main
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# on:
#   schedule:
#     - cron: "* * * * *"

# jobs:
#   scheduled-job:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: "18"
#       - run: pwd
#       - run: npm install
#       - run: node ./worker/dist/noon.js
